In [ ]:
# Using Python to access data from an API

In [ ]:
import requests
import pandas as pd
import json

In [ ]:
# requesting data from my API URL

In [ ]:
response = requests.get("https://power.larc.nasa.gov/api/temporal/daily/point?parameters=WS10M&community=SB&longitude=51.45904975&latitude=-2.603436197922635&start=20210110&end=20220110&format=JSON")

In [ ]:
# checking that the fetch was sucessful

In [ ]:
print(response.status_code)

200

In [ ]:
print(response.json())

{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [51.45904975, -2.603436197922635, 0.0]}, 'properties': {'parameter': {'WS10M': {'20210110': 6.6, '20210111': 5.58, '20210112': 6.11, '20210113': 5.41, '20210114': 3.62, '20210115': 3.49, '20210116': 3.7, '20210117': 4.23, '20210118': 5.88, '20210119': 5.62, '20210120': 3.44, '20210121': 3.24, '20210122': 3.15, '20210123': 3.66, '20210124': 5.51, '20210125': 5.14, '20210126': 4.26, '20210127': 4.04, '20210128': 4.59, '20210129': 5.53, '20210130': 3.89, '20210131': 4.28, '20210201': 6.07, '20210202': 6.22, '20210203': 5.16, '20210204': 4.42, '20210205': 4.84, '20210206': 4.7, '20210207': 5.09, '20210208': 5.25, '20210209': 5.3, '20210210': 6.49, '20210211': 5.8, '20210212': 4.81, '20210213': 4.46, '20210214': 5.33, '20210215': 5.41, '20210216': 6.16, '20210217': 5.35, '20210218': 5.86, '20210219': 7.08, '20210220': 5.86, '20210221': 4.6, '20210222': 4.98, '20210223': 5.75, '20210224': 4.74, '20210225': 3.83, '20210226': 4.58, '20210227': 5.48, '20210228': 4.68, '20210301': 4.3, '20210302': 3.58, '20210303': 4.5, '20210304': 6.02, '20210305': 5.59, '20210306': 5.65, '20210307': 5.09, '20210308': 5.12, '20210309': 4.13, '20210310': 3.89, '20210311': 3.12, '20210312': 2.76, '20210313': 2.44, '20210314': 1.05, '20210315': 1.42, '20210316': 3.69, '20210317': 3.73, '20210318': 2.77, '20210319': 2.9, '20210320': 2.53, '20210321': 3.05, '20210322': 2.8, '20210323': 1.8, '20210324': 2.07, '20210325': 2.1, '20210326': 3.52, '20210327': 2.44, '20210328': 1.47, '20210329': 1.57, '20210330': 1.91, '20210331': 2.57, '20210401': 2.08, '20210402': 1.27, '20210403': 2.24, '20210404': 2.49, '20210405': 1.49, '20210406': 1.85, '20210407': 1.89, '20210408': 1.84, '20210409': 1.95, '20210410': 2.08, '20210411': 2.27, '20210412': 2.17, '20210413': 2.62, '20210414': 2.25, '20210415': 1.95, '20210416': 0.89, '20210417': 1.44, '20210418': 1.55, '20210419': 1.7, '20210420': 3.31, '20210421': 3.03, '20210422': 1.28, '20210423': 2.7, '20210424': 3.48, '20210425': 2.77, '20210426': 2.68, '20210427': 2.58, '20210428': 3.27, '20210429': 2.88, '20210430': 2.05, '20210501': 1.6, '20210502': 2.19, '20210503': 0.97, '20210504': 1.3, '20210505': 2.1, '20210506': 3.58, '20210507': 6.69, '20210508': 5.02, '20210509': 3.84, '20210510': 5.05, '20210511': 5.0, '20210512': 5.93, '20210513': 5.42, '20210514': 5.88, '20210515': 5.08, '20210516': 5.81, '20210517': 6.33, '20210518': 7.78, '20210519': 8.6, '20210520': 8.74, '20210521': 8.65, '20210522': 7.41, '20210523': 7.77, '20210524': 6.95, '20210525': 6.96, '20210526': 6.06, '20210527': 5.12, '20210528': 4.9, '20210529': 3.34, '20210530': 5.14, '20210531': 6.69, '20210601': 6.53, '20210602': 6.67, '20210603': 7.1, '20210604': 5.7, '20210605': 4.3, '20210606': 4.7, '20210607': 6.13, '20210608': 7.74, '20210609': 7.34, '20210610': 7.33, '20210611': 6.49, '20210612': 5.95, '20210613': 6.62, '20210614': 5.78, '20210615': 5.92, '20210616': 6.57, '20210617': 6.98, '20210618': 7.11, '20210619': 7.89, '20210620': 7.67, '20210621': 7.19, '20210622': 7.7, '20210623': 7.08, '20210624': 7.68, '20210625': 7.16, '20210626': 7.8, '20210627': 7.69, '20210628': 7.42, '20210629': 7.8, '20210630': 8.3, '20210701': 7.47, '20210702': 7.57, '20210703': 8.41, '20210704': 8.59, '20210705': 7.42, '20210706': 9.46, '20210707': 8.91, '20210708': 7.91, '20210709': 8.7, '20210710': 8.58, '20210711': 7.92, '20210712': 7.35, '20210713': 9.23, '20210714': 9.2, '20210715': 8.5, '20210716': 8.46, '20210717': 7.56, '20210718': 7.01, '20210719': 7.78, '20210720': 6.16, '20210721': 8.27, '20210722': 8.95, '20210723': 8.6, '20210724': 9.56, '20210725': 8.55, '20210726': 6.65, '20210727': 6.28, '20210728': 8.4, '20210729': 8.97, '20210730': 7.59, '20210731': 6.96, '20210801': 9.17, '20210802': 7.86, '20210803': 7.54, '20210804': 8.75, '20210805': 8.21, '20210806': 6.41, '20210807': 5.15, '20210808': 6.64, '20210809': 6.88, '20210810': 6.44, '20210811': 4.61, '20210812': 3.01, '20210813': 4.48, '20210814': 8.18, '20210815': 8.46, '20210816': 8.7, '20210817': 7.98, '20210818': 6.13, '20210819': 5.78, '20210820': 7.98, '20210821': 7.79, '20210822': 7.45, '20210823': 6.64, '20210824': 8.41, '20210825': 8.23, '20210826': 7.59, '20210827': 6.07, '20210828': 7.84, '20210829': 6.2, '20210830': 3.73, '20210831': 5.72, '20210901': 6.88, '20210902': 7.69, '20210903': 6.8, '20210904': 6.84, '20210905': 6.66, '20210906': 5.66, '20210907': 6.51, '20210908': 8.5, '20210909': 7.12, '20210910': 7.36, '20210911': 9.96, '20210912': 8.52, '20210913': 6.64, '20210914': 6.62, '20210915': 7.66, '20210916': 6.73, '20210917': 6.13, '20210918': 7.12, '20210919': 6.83, '20210920': 6.7, '20210921': 5.88, '20210922': 7.34, '20210923': 6.74, '20210924': 7.59, '20210925': 7.1, '20210926': 6.07, '20210927': 6.98, '20210928': 4.84, '20210929': 6.36, '20210930': 7.41, '20211001': 6.33, '20211002': 6.49, '20211003': 6.12, '20211004': 5.9, '20211005': 6.68, '20211006': 6.06, '20211007': 5.38, '20211008': 4.7, '20211009': 6.61, '20211010': 5.62, '20211011': 6.35, '20211012': 6.66, '20211013': 3.97, '20211014': 4.94, '20211015': 6.66, '20211016': 5.48, '20211017': 5.07, '20211018': 6.09, '20211019': 5.75, '20211020': 5.18, '20211021': 3.05, '20211022': 1.41, '20211023': 1.5, '20211024': 2.99, '20211025': 2.98, '20211026': 5.52, '20211027': 5.54, '20211028': 3.12, '20211029': 1.66, '20211030': 0.78, '20211031': 1.77, '20211101': 2.7, '20211102': 2.89, '20211103': 3.24, '20211104': 3.34, '20211105': 3.83, '20211106': 2.96, '20211107': 1.54, '20211108': 1.64, '20211109': 1.05, '20211110': 2.52, '20211111': 2.22, '20211112': 1.03, '20211113': 2.91, '20211114': 3.7, '20211115': 3.89, '20211116': 3.16, '20211117': 3.05, '20211118': 2.21, '20211119': 3.2, '20211120': 2.98, '20211121': 1.6, '20211122': 2.66, '20211123': 3.47, '20211124': 2.6, '20211125': 1.62, '20211126': 2.69, '20211127': 2.73, '20211128': 3.55, '20211129': 3.39, '20211130': 3.2, '20211201': 4.3, '20211202': 3.9, '20211203': 3.16, '20211204': 3.05, '20211205': 3.25, '20211206': 3.66, '20211207': 3.63, '20211208': 4.28, '20211209': 4.07, '20211210': 2.7, '20211211': 0.93, '20211212': 1.1, '20211213': 3.27, '20211214': 4.09, '20211215': 2.48, '20211216': 2.11, '20211217': 1.71, '20211218': 2.8, '20211219': 3.41, '20211220': 2.76, '20211221': 2.79, '20211222': 2.12, '20211223': 3.17, '20211224': 1.76, '20211225': 2.3, '20211226': 3.74, '20211227': 3.73, '20211228': 6.07, '20211229': 5.79, '20211230': 6.08, '20211231': 5.98, '20220101': 5.89, '20220102': 3.9, '20220103': 4.25, '20220104': 5.3, '20220105': 4.95, '20220106': 5.24, '20220107': 4.83, '20220108': 5.71, '20220109': 5.79, '20220110': 4.98}}}, 'header': {'title': 'NASA/POWER CERES/MERRA2 Native Resolution Daily Data', 'api': {'version': 'v2.2.15', 'name': 'POWER Daily API'}, 'fill_value': -999.0, 'start': '20210110', 'end': '20220110'}, 'messages': [], 'parameters': {'WS10M': {'units': 'm/s', 'longname': 'Wind Speed at 10 Meters'}}, 'times': {'data': 2.394, 'process': 0.02}}

In [ ]:
data = response.json()
data

In [ ]:
from pandas import json_normalize

In [ ]:
# using json normalise to load my json data into a flat table

In [ ]:
df = json_normalize(data)

In [ ]:
df

      type messages  ... times.data times.process
0  Feature       []  ...      2.394          0.02

[1 rows x 380 columns]

In [ ]:
df = df.T

In [ ]:
df

                                                                          0
type                                                                Feature
messages                                                                 []
geometry.type                                                         Point
geometry.coordinates                 [51.45904975, -2.603436197922635, 0.0]
properties.parameter.WS10M.20210110                                     6.6
...                                                                     ...
header.end                                                         20220110
parameters.WS10M.units                                                  m/s
parameters.WS10M.longname                           Wind Speed at 10 Meters
times.data                                                            2.394
times.process                                                          0.02

[380 rows x 1 columns]

In [1]:
# dropping meta information for tidy data

In [ ]:
df = df.iloc[4: , :]

In [ ]:
df

                                                           0
properties.parameter.WS10M.20210110                      6.6
properties.parameter.WS10M.20210111                     5.58
properties.parameter.WS10M.20210112                     6.11
properties.parameter.WS10M.20210113                     5.41
properties.parameter.WS10M.20210114                     3.62
...                                                      ...
header.end                                          20220110
parameters.WS10M.units                                   m/s
parameters.WS10M.longname            Wind Speed at 10 Meters
times.data                                             2.394
times.process                                           0.02

[376 rows x 1 columns]

In [ ]:
df = df.iloc[:-12]

In [ ]:
df

                                        0
properties.parameter.WS10M.20210110   6.6
properties.parameter.WS10M.20210111  5.58
properties.parameter.WS10M.20210112  6.11
properties.parameter.WS10M.20210113  5.41
properties.parameter.WS10M.20210114  3.62
...                                   ...
properties.parameter.WS10M.20220104   5.3
properties.parameter.WS10M.20220105  4.95
properties.parameter.WS10M.20220106  5.24
properties.parameter.WS10M.20220107  4.83
properties.parameter.WS10M.20220108  5.71

[364 rows x 1 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 364 entries, properties.parameter.WS10M.20210110 to properties.parameter.WS10M.20220108
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       364 non-null    object
dtypes: object(1)
memory usage: 5.7+ KB

In [ ]:
df = df.reset_index()

In [ ]:
df

                                   index     0
0    properties.parameter.WS10M.20210110   6.6
1    properties.parameter.WS10M.20210111  5.58
2    properties.parameter.WS10M.20210112  6.11
3    properties.parameter.WS10M.20210113  5.41
4    properties.parameter.WS10M.20210114  3.62
..                                   ...   ...
359  properties.parameter.WS10M.20220104   5.3
360  properties.parameter.WS10M.20220105  4.95
361  properties.parameter.WS10M.20220106  5.24
362  properties.parameter.WS10M.20220107  4.83
363  properties.parameter.WS10M.20220108  5.71

[364 rows x 2 columns]

In [ ]:
df = df.rename(columns={0: "wind"})

In [ ]:
df

                                   index  wind
0    properties.parameter.WS10M.20210110   6.6
1    properties.parameter.WS10M.20210111  5.58
2    properties.parameter.WS10M.20210112  6.11
3    properties.parameter.WS10M.20210113  5.41
4    properties.parameter.WS10M.20210114  3.62
..                                   ...   ...
359  properties.parameter.WS10M.20220104   5.3
360  properties.parameter.WS10M.20220105  4.95
361  properties.parameter.WS10M.20220106  5.24
362  properties.parameter.WS10M.20220107  4.83
363  properties.parameter.WS10M.20220108  5.71

[364 rows x 2 columns]

In [ ]:
df = df.rename(columns={"index": "date"})

In [ ]:
df

                                    date  wind
0    properties.parameter.WS10M.20210110   6.6
1    properties.parameter.WS10M.20210111  5.58
2    properties.parameter.WS10M.20210112  6.11
3    properties.parameter.WS10M.20210113  5.41
4    properties.parameter.WS10M.20210114  3.62
..                                   ...   ...
359  properties.parameter.WS10M.20220104   5.3
360  properties.parameter.WS10M.20220105  4.95
361  properties.parameter.WS10M.20220106  5.24
362  properties.parameter.WS10M.20220107  4.83
363  properties.parameter.WS10M.20220108  5.71

[364 rows x 2 columns]

In [ ]:
# using a for loop to iterate over the date column, to isolate the date information

In [ ]:
for x in range(0,len(df)):
  df['date'][x] = df['date'][x][27:]

In [ ]:
df

         date  wind
0    20210110   6.6
1    20210111  5.58
2    20210112  6.11
3    20210113  5.41
4    20210114  3.62
..        ...   ...
359  20220104   5.3
360  20220105  4.95
361  20220106  5.24
362  20220107  4.83
363  20220108  5.71

[364 rows x 2 columns]

In [ ]:
import pandas as pd

In [ ]:
df["date"] = pd.to_datetime(df["date"])

In [ ]:
df

          date  wind
0   2021-01-10   6.6
1   2021-01-11  5.58
2   2021-01-12  6.11
3   2021-01-13  5.41
4   2021-01-14  3.62
..         ...   ...
359 2022-01-04   5.3
360 2022-01-05  4.95
361 2022-01-06  5.24
362 2022-01-07  4.83
363 2022-01-08  5.71

[364 rows x 2 columns]

In [ ]:
df.to_csv("senate_wind.csv", index = False)

In [ ]:
from google.colab import files

In [ ]:
files.download("senate_wind.csv")